version: "3.7"

services:
  traefik:
    image: traefik:v3.3.3
    container_name: "traefik"
    ports:
      - "80:80"    # Expose HTTP
      - "443:443" #dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"  # Access Docker event
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./rules.yml:/etc/traefik/conf.d/rules.yml"
      #You need to create the acme.json file with file permission of 600
      - "./acme.json:/acme.json"
    networks:
      - main
  service-01:
    image: docker/getting-started
    #listens on port 80
    container_name: "service-01"
    networks:
      - main
  service-02:
    image: "traefik/whoami"
    container_name: "service-02"
    #listens on port 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`service-02.demo.faithtosin.cloud`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=resolver-01"
    networks:
      - main
networks:
  main:
    external: false
